api/urls.py
from django.conf.urls import url
from api.views import *


urlpatterns = [
	url(r'^list/$', PostListAPIView.as_view(), name="list"),
	url(r'^create/$', PostCreateAPIView.as_view(), name="create"),
	url(r'^comment/list/$', CommentListAPIView.as_view(), name="comment_list"),
	url(r'^comment/create/$', CommentCreateAPIView.as_view(), name="comment_create"),
	url(r'^register/$', UserCreateAPIView.as_view(), name="register"),
	url(r'^login/$', UserLoginAPIView.as_view(), name="login"),
	url(r'^detail/(?P<post_slug>[-\w]+)/$', PostDetailAPIView.as_view(), name="detail"),
	url(r'^delete/(?P<post_slug>[-\w]+)/$', PostDeleteAPIView.as_view(), name="delete"),
	url(r'^update/(?P<post_slug>[-\w]+)/$', PostUpdateAPIView.as_view(), name="update"),
]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^posts/', include('posts.urls', namespace="posts")),
	url(r'^comments/', include('django_comments.urls')),
	url(r'^api/', include('api.urls', namespace="api")),
	url(r'^googleapp/', include('googleapp.urls', namespace="googleapp")),
	url(r'^accounts/', include('allauth.urls')),
	url(r'^github/', include('githubapp.urls', namespace="github")),
	url(r'^twitter/', include('twitterapp.urls', namespace="twitter")),
]
if settings.DEBUG:
	urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^create/$', views.post_create, name="create"),
	url(r'^list/$', views.post_list, name="list"),
	url(r'^detail/(?P<post_slug>[-\w]+)/$', views.post_detail, name="detail"),
	url(r'^update/(?P<post_slug>[-\w]+)/$', views.post_update, name="update"),
	url(r'^delete/(?P<post_slug>[-\w]+)/$', views.post_delete, name="delete"), 
	url(r'^ajax_like/(?P<post_id>\d+)/$', views.ajax_like, name="like_button"),
	url(r'^signup/$', views.usersignup, name="signup"),
	url(r'^login/$', views.userlogin, name="login"),
	url(r'^logout/$', views.userlogout, name="logout"),
]

posts/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify
from django.db.models.signals import pre_save
from django.contrib.auth.models import User

class Post(models.Model):
	author = models.ForeignKey(User, default=1)
	title = models.CharField(max_length=20)
	slug = models.SlugField(unique=True)
	image = models.ImageField(null=True, blank=True, upload_to="post_images")
	content = models.TextField()
	draft = models.BooleanField(default=False)
	publish = models.DateField(auto_now=False, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=True)
	updated = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('posts:detail', kwargs={"post_slug": self.slug})	

	class Meta:
		ordering = ["-timestamp", "-updated"]

def create_slug(instance, new_slug=None):
	slug = slugify (instance.title)
	if new_slug is not None:
		slug = new_slug
	qs = Post.objects.filter(slug=slug).order_by("-id")
	exists = qs.exists()
	if exists:
		new_slug = "%s-%s"%(slug,qs.first().id)
		return create_slug(instance, new_slug=new_slug)
	return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug=create_slug(instance)

pre_save.connect(pre_save_post_receiver,sender=Post)	

class Like(models.Model):
	user = models.ForeignKey(User)
	post = models.ForeignKey(Post)
	created = models.DateTimeField(auto_now_add=True)

posts/forms.py
from django import forms 
from .models import Post 
from django.contrib.auth.models import User

class PostForm(forms.ModelForm):
	class Meta:
		model = Post 
		fields = ['title', 'content', 'image', 'draft', 'publish']

		widgets={
		'publish': forms.DateInput(attrs={"type":"date"}),
		}
		
class UserSignup(forms.ModelForm):
	class Meta:
		model = User
		fields = ['username','password']

		widgets={
		'password': forms.PasswordInput(),
		}

class UserLogin(forms.Form):
	username = forms.CharField(required=True)
	password = forms.CharField(required=True, widget=forms.PasswordInput())		

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Like
from .forms import PostForm
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from urllib.parse import quote
from django.http import Http404, JsonResponse
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models import Q
from .forms import UserSignup, UserLogin
from django.contrib.auth import authenticate, login, logout

def usersignup(request):
	context = {}
	form = UserSignup()
	context['form'] = form
	if request.method == 'POST':
		form = UserSignup(request.POST)
		if form.is_valid():
			user = form.save()
			username = user.username
			password = user.password

			user.set_password(password)
			user.save()

			auth_user = authenticate(username=username, password=password)
			login(request, auth_user)

			return redirect("posts:list")
		messages.error(request, form.errors)
		return redirect("posts:signup")
	return render(request, 'signup.html', context)

def userlogin(request):
	context = {}
	form = UserLogin()
	context['form'] = form
	if request.method == 'POST':
		form = UserLogin(request.POST)
		if form.is_valid():

			username = form.cleaned_data['username']
			password = form.cleaned_data['password']

			auth_user = authenticate(username=username, password=password)
			if auth_user is not None:
				login(request, auth_user)
				return redirect('posts:list')

			messages.error(request, "Wrong username/password combination. Please try again.")
			return redirect("posts:login")
		messages.error(request, form.errors)
		return redirect("posts:login")
	return render(request, 'login.html', context)

def userlogout(request):
	logout(request)
	return redirect("posts:list")
		

def ajax_like(request, post_id):
	post_object = Post.objects.get(id=post_id)
	new_like, created = Like.objects.get_or_create(user=request.user, post=post_object)

	if created:
		action="like"
	else:
		new_like.delete()
		action="unlike"

	post_like_count = post_object.like_set.all().count()
	response = {
		"action": action,
		"post_like_count": post_like_count,
	}
	return JsonResponse(response, safe=False)

def post_create(request):
	if not (request.user.is_staff or request.user.is_superuser):
		raise Http404
	form = PostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		post = form.save(commit = False)
		post.author = request.user
		form.save()
		messages.success(request, "Succesfuly Created")
		return redirect("posts:list")
	context = {
	"title": "Create",
	"form": form,
	}
	return render(request, 'post_create.html', context)

def post_delete(request, post_slug):
	if not (request.user.is_staff or request.user.is_superuser):
		raise Http404
	instance = get_object_or_404(Post, slug=post_slug)
	instance.delete()
	messages.warning(request, "Succesfully Deleted")
	return redirect("posts:list")

def post_detail(request, post_slug):
	instance = get_object_or_404(Post, slug=post_slug)
	if instance.publish>timezone.now().date() or instance .draft:
		if not (request.user.is_staff or request.user.is_superuser):
			raise Http404
	if request.user.is_authenticated():
		if Like.objects.filter(post=instance, user=request.user).exists():
			liked = True
		else:
			liked = False
	post_like_count = instance.like_set.all().count()

	context = {
	"instance" : instance,
	"share_string": quote(instance.content),
	"post_like_count": post_like_count,
	"liked":liked,
	}
	return render(request, 'post_detail.html', context)

def post_list(request):
	today = timezone.now().date()
	object_list = Post.objects.filter(draft=False).filter(publish__lte=today)
	if request.user.is_staff or request.user.is_superuser:
		object_list = Post.objects.all()

	query = request.GET.get("q")
	if query:
			object_list = object_list.filter(
			Q(title__icontains=query)|
			Q(content__icontains=query)|
			Q(author__first_name__icontains=query)|
			Q(author__last_name__icontains=query)
			).distinct()
			
	paginator = Paginator(object_list, 5)
	page = request.GET.get('page')
	try:
		objects = paginator.page(page)
	except PageNotAnInteger:
		objects=paginator.page(1)
	except EmptyPage:
		objects = paginator.page(paginator.num_pages)		
	context = {
	"object_list": objects,
	"title": "List",
	"user": request.user,
	"today": today,
	}
	return render(request, 'post_list.html', context)

def post_update(request, post_slug):
	if not (request.user.is_staff or request.user.is_superuser):
		raise Http404
	instance = get_object_or_404(Post, slug=post_slug)
	form = PostForm(request.POST or None, request.FILES or None, instance= instance)
	if form.is_valid():
		form.save()
		messages.success(request, "Succesfuly Updated")
		return redirect(instance.get_absolute_url())
	context = {
	"form": form,
	"instance": instance,
	"title": "Update",
	}	
	return render(request, 'post_update.html', context)			

posts/templates/base.html
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>
	{% block title %}

	{% endblock title %}
	</title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
	{% include "facebook_comments.html" %}
	{% include "navbar.html" %}
	{% include "messages.html" %}

	<div class="container">

	{% block content %}


	{% endblock content %}
	
	</div>
	<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

posts/templates/django_comments.html
{% load comments %}
{% get_comment_list for instance as comments %}

{% for comment in comments %}
	<div class="alert alert-info" role="alert"><b>{{ comment.user_name }} said:</b> {{ comment.comment|linebreaks}}</div>
{% endfor %}

{% get_comment_form for instance as form %}
<form action="{% comment_form_target %}" method="POST">
	{% csrf_token %}
	<input type="hidden" name="name" value="{{ request.user.username }}">
	<input type="hidden" name="email" value="{{ request.user.email }}">
	<input type="text" class="form-control input-lg" name="comment">
	{{ form.content_type }}
	{{ form.object_pk }}
	{{ form.timestamp }}
	{{ form.security_hash }}
	<input type="hidden" name="next" value="{{instance.get_absolute_url}}"><br>
	<input type="submit" name="submit" class="btn btn-primary">
</form>

posts/templates/facebook_comments.html
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.10";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

posts/templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
Login
{% endblock title %}


{% block content %}
    <form action="{% url 'posts:login' %}" method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input class = "btn btn-primary" type="submit" value="Login">
    </form>
{% endblock content %}

posts/templates/messages.html
{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}

posts/templates/navbar.html
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'posts:list' %}">Practice Blog</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'posts:login' %}">Login</a></li>
        <li><a href="{% url 'posts:signup' %}">Sign Up</a></li>
        <li><a href="{% url 'posts:logout' %}">Logout</a></li>
        {% if request.user.is_staff or request.user.is_superuser %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Other Pages <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'posts:create' %}">Create Post</a></li>
            <li><a href="/admin">Admin</a></li>
          </ul>
        </li>
        {% endif %}
      </ul>
      <form class="navbar-form navbar-left" ction="{% url 'posts:list' %}" method="GET" value="{{request.GET.q}}">
        <div class="form-group">
          <input type="text" name="q" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

posts/templates/post_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
	Create
{% endblock title %}


{% block content %}

	<h1> The Post {{title}} Page </h1>
	<form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{form|crispy}}
	<input type="submit" value="Create Post">
	</form>
	
{% endblock content %}

posts/templates/post_delete.html
<!DOCTYPE html>
<html>
<head>
	<title>Post</title>
</head>
<body>

</body>
</html>

posts/templates/post_detail.html
{% extends "base.html" %}
{% load urlify %}

{% block title %}
	Detail
{% endblock title %}


{% block content %}

<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
		<div class="thumbnail">
		{% if instance.image %}
			<img src="{{instance.image.url}}" alt="" class="img-responsive">
		{% endif %}
			<div class="caption">
				<h3>{{instance.title}}</a><small> {{instance.publish|timesince}} ago</small></h3>
				<p>{{instance.content|linebreaks|truncatechars:100}}</p>
				Author: {{instance.author.get_full_name}} <br><br>
				<a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}">Share on Facebook</a><br>
				<a href="https://twitter.com/home?status={{share_string}}%20{{request.build_absolute_uri}}">Share on Twitter</a><br>
				<a href="https://www.linkedin.com/shareArticle?mini=true&url={{request.build_absolute_uri}}&title={{instance.title|urlify}}&summary={{instance.content|truncatechars:35|urlify}}&source={{request.build_absolute_uri}}">Share on Linkedin</a><br><br>

				<button class="btn" onclick="ajax_like()">
					<span id="likes_count">{{ post_like_count }}</span>
					<span id= "heart" class="glyphicon glyphicon-heart {% if liked %}text-danger{% endif %}" aria-hidden="true"></span>
				</button>
				

				<br><br>
				{# {% include "django_comments.html" %} #}
			</div>
		</div>
		<div class="fb-like col-sm-12" data-href="{{request.build_absolute_uri}}" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
		<div class="fb-comments col-sm-12" data-href="{{request.build_absolute_uri}}" data-numposts="5"></div></div>
	</div>
</div>


<script type="text/javascript">
	function ajax_like() {
		console.log("Like/Unlike clicked!");
		$.ajax(
			{
				type:'GET',
				url: '{% url "posts:like_button" post_id=instance.id %}',
				error: function(){
					console.log('error');
				},
				success: function(data){ 
					$("#likes_count").text(data.post_like_count);

					if(data.action==="like"){
						$("#heart").addClass("text-danger");
					}else{
						$("#heart").removeClass("text-danger")  
					}
				},
			}
		);
	}
</script>
{% endblock content %}

posts/templates/post_list.html
{% extends "base.html" %}

{% block title %}
	List
{% endblock title %}


{% block content %}

<div class="row">
{% for object in object_list %}
  <div class="col-sm-6 col-md-4">
	<div class="thumbnail">
	{% if object.image %}
	  <img src="{{object.image.url}}" class="img-responsive">
	{% endif %}  
	  <div class="caption">
		<h3><a href="{{ object.get_absolute_url }}">{{object.title}}</a><small> {{object.publish|timesince}} ago</small></h3>
		{% if object.draft %}<h3>Draft</h3>{% endif %}
		{% if object.publish > today %}<h3>Future Post</h3>{% endif %}
		<p>{{object.content|linebreaks|truncatechars:100}}</p>
		<p><a href="{{ object.get_absolute_url }}" class="btn btn-primary" role="button">
		View</a>
		<a href="{% url 'posts:update' post_slug=object.slug %}" class="btn btn-success">Edit</a>
		<a href="{% url 'posts:delete' post_slug=object.slug %}" class="btn btn-danger">Delete</a>  
	  </div>
	</div>
  </div> 

	{% endfor %}
</div>    
<div class="pagination">
		<span class="step-links">
			{% if object_list.has_previous %}
				<a href="?page={{ object_list.previous_page_number }}&q={{ request.GET.q }}">previous</a>
			{% endif %}

			<span class="current">
				Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
			</span>

			{% if object_list.has_next %}
				<a href="?page={{ object_list.next_page_number }}&q={{ request.GET.q }}">next</a>
			{% endif %}
		</span>
</div>       
{% endblock content %}

posts/templates/post_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Update
{% endblock title %}


{% block content %}

	<h1> The Post {{title}} Page </h1>
	<form action="{% url 'posts:update' post_slug=instance.slug %}" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{form|crispy}}
	<input type="submit" value="Update Post">
	</form>

{% endblock content %}

posts/templates/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
Sign Up
{% endblock title %}


{% block content %}
    <form action="{% url 'posts:signup' %}" method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input class = "btn btn-primary" type="submit" value="Sign Up">
    </form>
{% endblock content %}