api/urls.py
from django.conf.urls import url
from api.views import *


urlpatterns = [
	url(r'^list/$', PostListAPIView.as_view(), name="list"),
	url(r'^create/$', PostCreateAPIView.as_view(), name="create"),
	url(r'^comment/list/$', CommentListAPIView.as_view(), name="comment_list"),
	url(r'^comment/create/$', CommentCreateAPIView.as_view(), name="comment_create"),
	url(r'^register/$', UserCreateAPIView.as_view(), name="register"),
	url(r'^login/$', UserLoginAPIView.as_view(), name="login"),
	url(r'^detail/(?P<post_slug>[-\w]+)/$', PostDetailAPIView.as_view(), name="detail"),
	url(r'^delete/(?P<post_slug>[-\w]+)/$', PostDeleteAPIView.as_view(), name="delete"),
	url(r'^update/(?P<post_slug>[-\w]+)/$', PostUpdateAPIView.as_view(), name="update"),
]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^posts/', include('posts.urls', namespace="posts")),
	url(r'^comments/', include('django_comments.urls')),
	url(r'^api/', include('api.urls', namespace="api")),
	url(r'^googleapp/', include('googleapp.urls', namespace="googleapp")),
	url(r'^accounts/', include('allauth.urls')),
	url(r'^github/', include('githubapp.urls', namespace="github")),
	url(r'^twitter/', include('twitterapp.urls', namespace="twitter")),
]
if settings.DEBUG:
	urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

googleapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

	url(r'^text/$', views.text_search,name="text"),
	url(r'^detail/$', views.place_detail, name="detail"),
	url(r'^nearby/$', views.nearby_search, name="nearby"),
]

googleapp/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests

def text_search(request):
	api_key = "AIzaSyAOuEU_qz6RyeuvfDpLw0IaDSywp46Rtu0"
	query = request.GET.get("query", '')
	next_page_token = request.GET.get("next_page_token")
	url = 'https://maps.googleapis.com/maps/api/place/textsearch/json?query=%s&key=%s'%(query, api_key)
	
	if next_page_token is not None:
			url += "&pagetoken=%s"%(next_page_token)

	response = requests.get(url)
	
	context = {
		"response":response.json(),
	}
	return render(request, 'text.html', context)

def place_detail(request):
	api_key = "AIzaSyAOuEU_qz6RyeuvfDpLw0IaDSywp46Rtu0"
	query = request.GET.get("reference")
	key = 'AIzaSyDBzLV40ne47V_C50u34jQBnM6zVHeZ-Hc'
	url = "https://maps.googleapis.com/maps/api/place/details/json?reference=%s&key=%s"%(query, api_key)
	response = requests.get(url)

	context = {
		"response": response.json(),
		"key": key,
	}

	return render(request, 'detail.html', context)

def nearby_search(request):
	api_key = "AIzaSyAOuEU_qz6RyeuvfDpLw0IaDSywp46Rtu0"
	location = request.GET.get("location")
	radius = request.GET.get("radius", '')
	# url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-33.8670522,151.1957362&radius=500&key=AIzaSyAOuEU_qz6RyeuvfDpLw0IaDSywp46Rtu0"
	url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=%s&radius=%s&key=%s'%(location, radius, api_key)
	response = requests.get(url)

	context = {
		"response":response.json(),
	}

	return render(request, 'nearby.html', context)

googleapp/templates/detail.html
{% extends "base.html" %}

{% block content %}

<br><br><br>
	<h1>STATUS : {{response.status}}</h1>

	<table class="table">
		<tr>
			<td>{{response.result.name}}</td>
			<td>{{response.result.formatted_address}}</td>
			<td>{{response.result.website}}</td>
		</tr>
	</table>

	<iframe
	id="map"
	width="600"
	height="450"
	frameborder="0" style="border:0"
	src="" allowfullscreen>
	</iframe>	
	
	<script>
	var options = {
	  enableHighAccuracy: true,
	  timeout: 5000,
	  maximumAge: 0
	};

	function success(pos) {
	  var crd = pos.coords;

	  var map = $("#map");
	  map.attr('src', 'https://www.google.com/maps/embed/v1/directions?key={{ key }}&origin='+crd.latitude+','+crd.longitude+'&destination={{response.result.geometry.location.lat}}','{{response.result.geometry.location.lng}}')
	  
	};

	function error(err) {
	  console.warn("Error");
	};

	navigator.geolocation.getCurrentPosition(success, error, options);
	</script>

{% endblock content %}

googleapp/templates/nearby.html
{% extends "base.html" %}

{% block content %}

	<h1>STATUS : {{response.status}}</h1>
	<form action="{% url 'googleapp:nearby' %}" method="GET">
		<input type="text" name="radius" placeholder="Set Radius">
		<input type="submit" value="Search" class="btn btn-primary">
		<input type="hidden" name="location" value="" id="location">
	</form>
	<table>
		{% for result in response.results  %}
			<tr>
			<td>{{result.name}}</td>
			<td>	
		{% endfor %}
	</table>	

	<script>
		var options = {
		  enableHighAccuracy: true,
		  timeout: 5000,
		  maximumAge: 0
		};

		function success(pos) {
		  var crd = pos.coords;
		  $("#location").val(crd.latitude+','+crd.longitude);

		};

		function error(err) {
		  console.warn(`ERROR(${err.code}): ${err.message}`);
		};

		navigator.geolocation.getCurrentPosition(success, error, options);
	</script>	


{% endblock content %}

googleapp/templates/text.html
{% extends "base.html" %}

{% block content %}

	<h1>STATUS : {{response.status}}</h1>
	<form action="{% url 'googleapp:text' %}" method="GET">
		<input type="text" name="query" placeholder="search for a place">
		<input type="submit" value="Search" class="btn btn-primary">
	</form>
	<form action="{% url 'googleapp:text' %}" method="GET">
		<input type="hidden" name="next_page_token" value="{{response.next_page_token}}">
		<input type="submit" value="Next Page" class="btn btn-primary">
	</form>
	<table>
		{% for result in response.results  %}
			<tr>
			<td>{{result.name}}</td>
			<td>	
			<form action="{% url 'googleapp:detail' %}" method="GET">
				<input type="hidden" name="reference" value="{{result.reference}}">
				<input type="submit" value="More Info" class="btn btn-primary">
			</tr>
		{% endfor %}
	</table>
{% endblock content %}